all:
  hosts:
    node1:
      ansible_host: 192.168.0.194
      ip: 192.168.0.194
      access_ip: 192.168.0.194
    node2:
      ansible_host: 192.168.0.195
      ip: 192.168.0.195
      access_ip: 192.168.0.195
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr: 
      hosts: {}
